config/routes.rb
Project1::Application.routes.draw do
  resources :companies

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table cellpadding="5" cellspacing="0" align="center" class="disp_data" style="width:900px;">
      <tr>
        <td width="50%">
            <table width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <td class="td_width main_title" colspan="2"><b>Company Details:</b></td>
              </tr>
              <tr>
                <td class="td_height_form"></td>
              </tr>
              <tr>
                <td class="td_width"><b>Group Name:</b></td><td><%= f.text_field :group_name %></td>
              </tr>
              <tr>
                <td class="td_width"><b>Company Name:</b></td><td><%= f.text_field :company_name %></td>
              </tr>
              <tr>
                <td class="td_width"><b>Establishment Date:</b></td><td><%= f.date_select :establishment_date %></td>
              </tr>
              <tr>
                <td class="td_width"><b>Company Logo:</b></td><td><%= f.text_field :company_logo %></td>
              </tr>
              <tr>
                <td class="td_height_form"></td>
              </tr>
              <tr>
                <td class="td_width main_title" colspan="2"><b>Address Details:</b></td>
              </tr>
              <tr>
                <td class="td_height_form" colspan="2"></td>
              </tr>
              <tr>
                <td class="td_width"><b>Address:</b></td><td><%= f.text_field :address %></td>
              </tr>
              <tr>
                <td class="td_width"><b>State:</b></td><td><%= f.text_field :state %></td>
              </tr>
              <tr>
                <td class="td_height_form"></td>
              </tr>
              <tr>
                <td class="td_width main_title" colspan="2"><b>Contact Details:</b></td>
              </tr>
              <tr>
                <td class="td_height_form" colspan="2"></td>
              </tr>
              <tr>
                <td class="td_width"><b>Contact No:</b></td><td><%= f.number_field :contact_one %></td>
              </tr>
              <tr>
                <td class="td_width"><b>Email:</b></td><td><%= f.text_field :email %></td>
              </tr>
              <tr>
                <td class="td_width"><b>Fax:</b></td><td><%= f.number_field :fax %></td>
              </tr>
            </table>
        </td>
        <td width="50%">
            <table width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <td class="td_width"></td>
              </tr>
              <tr>
                <td class="td_height_form"></td>
              </tr>
              <tr>
                <td class="td_width"></td>
              </tr>
              <tr>
                <td class="td_width"><b>Responsible Person:</b></td><td><%= f.text_field :responsible_person %></td>
              </tr>
              <tr>
                <td class="td_width"><b>Company Type:</b></td><td><%= f.text_field :company_type %></td>
              </tr>
              <tr>
                <td class="td_width"></td><td></td>
              </tr>
              <tr>
                <td class="td_height_form"></td>
              </tr>
              <tr>
                <td class="td_width"></td>
              </tr>
              <tr>
                <td class="td_height_form"></td>
              </tr>
              <tr>
                <td class="td_width"><b>City:</b></td><td><%= f.text_field :city %></td>
              </tr>
              <tr>
                <td class="td_width"><b>Country:</b></td><td><%= f.text_field :country %></td>
              </tr>
              <tr>
                <td class="td_height_form"></td>
              </tr>
              <tr>
                <td class="td_width"></td>
              </tr>
              <tr>
                <td class="td_height_form"></td>
              </tr>
              <tr>
                <td class="td_width"><b>Alternate No:</b></td><td><%= f.number_field :contact_two %></td>
              </tr>
              <tr>
                <td class="td_width"><b>Alternate Email:</b></td><td><%= f.text_field :email2 %></td>
              </tr>
              <tr>
                <td class="td_width"><b>Website:</b></td><td><%= f.text_field :website %></td>
              </tr>
            </table>
        </td>
      </tr>
      <tr><td class="td_height_form"></td></tr>
      <tr><td class="td_height_form"></td></tr>
      <tr><td class="td_height_form"><div class="actions"><%= f.submit %></div></td></tr>
  </table>

<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing Companies</h1>

<table align="center" cellpadding="0" cellspacing="0" width="900">
  <tr>
    <th class="b">Group name</th>
    <th class="btrb">Company name</th>
    <th class="btrb">Responsible person</th>
    <th class="btrb">Establishment date</th>
    <th class="btrb">Company type</th>
    <!--<th>Company logo</th>-->
    <!--<th>Address</th>-->
    <!--<th>City</th>-->
    <!--<th>State</th>-->
    <!--<th>Country</th>-->
    <!--<th>Contact one</th>-->
    <!--<th>Contact two</th>-->
    <!--<th>Fax</th>-->
    <!--<th>Email</th>-->
    <!--<th>Alternate Email</th>-->
    <!--<th>Website</th>-->
    <th colspan="3" class="btrb">Operation</th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td class="blrb"><%= company.group_name %></td>
    <td class="brb"><%= company.company_name %></td>
    <td class="brb"><%= company.responsible_person %></td>
    <td class="brb"><%= l company.establishment_date, :format => :default %></td>
    <td class="brb"><%= company.company_type %></td>
    <!--<td><%= company.company_logo %></td>-->
    <!--<td><%= company.address %></td>-->
    <!--<td><%= company.city %></td>-->
    <!--<td><%= company.state %></td>-->
    <!--<td><%= company.country %></td>-->
    <!--<td><%= company.contact_one %></td>-->
    <!--<td><%= company.contact_two %></td>-->
    <!--<td><%= company.fax %></td>-->
    <!--<td><%= company.email %></td>-->
    <!--<td><%= company.email2 %></td>-->
    <!--<td><%= company.website %></td>-->
    <td class="brb"><%= link_to 'Show', company %></td>
    <td class="brb"><%= link_to 'Edit', edit_company_path(company) %></td>
    <td class="brb"><%= link_to 'Destroy', company, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Company Details</h1>

<table cellpadding="5" cellspacing="0" align="center" class="disp_data">
  <tr>
    <td width="50%">
        <table width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <td class="td_width main_title" colspan="2"><b>Company Details:</b></td>
          </tr>
          <tr>
            <td class="td_width"><b>Group Name:</b></td><td><%= @company.group_name %></td>
          </tr>
          <tr>
            <td class="td_width"><b>Company Name:</b></td><td><%= @company.company_name %></td>
          </tr>
          <tr>
            <td class="td_width"><b>Establishment Date:</b></td><td><%= l @company.establishment_date, :format => :default %></td>
          </tr>
          <tr>
            <td class="td_width"><b>Company Logo:</b></td><td><%= @company.company_logo %></td>
          </tr>
          <tr>
            <td class="td_width main_title" colspan="2"><b>Address Details:</b></td>
          </tr>
          <tr>
            <td class="td_width"><b>Address:</b></td><td><%= @company.address %></td>
          </tr>
          <tr>
            <td class="td_width"><b>State:</b></td><td><%= @company.state %></td>
          </tr>
          <tr>
            <td class="td_width main_title" colspan="2"><b>Contact Details:</b></td>
          </tr>
          <tr>
            <td class="td_width"><b>Contact No:</b></td><td><%= @company.contact_one %></td>
          </tr>
          <tr>
            <td class="td_width"><b>Email:</b></td><td><%= @company.email %></td>
          </tr>
          <tr>
            <td class="td_width"><b>Fax:</b></td><td><%= @company.fax %></td>
          </tr>
        </table>
    </td>
    <td width="50%">
        <table width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <td class="td_width"></td>
          </tr>
          <tr>
            <td class="td_width"></td>
          </tr>
          <tr>
            <td class="td_width"><b>Responsible Person:</b></td><td><%= @company.responsible_person %></td>
          </tr>
          <tr>
            <td class="td_width"><b>Company Type:</b></td><td><%= @company.company_type %></td>
          </tr>
          <tr>
            <td class="td_width"></td><td>&nbsp;</td>
          </tr>
          <tr>
            <td class="td_width"></td><td>&nbsp;</td>
          </tr>
          <tr>
            <td class="td_width"><b>City:</b></td><td><%= @company.city %></td>
          </tr>
          <tr>
            <td class="td_width"><b>Country:</b></td><td><%= @company.country %></td>
          </tr>
          <tr>
            <td class="td_width"></td>
          </tr>
          <tr>
            <td class="td_width"><b>Alternate No:</b></td><td><%= @company.contact_two %></td>
          </tr>
          <tr>
            <td class="td_width"><b>Alternate Email:</b></td><td><%= @company.email2 %></td>
          </tr>
          <tr>
            <td class="td_width"><b>Website:</b></td><td><%= @company.website %></td>
          </tr>
        </table>
    </td>
  </tr>
</table>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project1</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>